// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnetqlelkrxhssbjzoki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZXRxbGVsa3J4aHNzYmp6b2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzQ4NjAsImV4cCI6MjA2MTMxMDg2MH0.JH-13Gq8ZVFsXQ2g1pNcuAMG93Om4g7IlV8t5MM9nEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);